apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-nginx
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: edge-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "phoenix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: edge-nginx
  template:
    metadata:
      labels:
        {{- include "phoenix.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: edge-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          limits:
            memory: 64Mi
      volumes:
      - name: nginx-config
        configMap:
          name: edge-nginx-config
