apiVersion: v1
kind: Service
metadata:
  name: phoenix-pipeline-worker
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix-pipeline-worker
spec:
  type: ClusterIP
  selector:
    {{- include "phoenix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix-pipeline-worker
  ports:
  - port: 8055
    targetPort: 8055
    name: http
