apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rh-tokens
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix-broker-gateway
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
