apiVersion: v1
kind: Service
metadata:
  name: phoenix-ws-gateway
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix-ws-gateway
spec:
  type: ClusterIP
  ports:
  - port: 8031
    targetPort: 8031
    protocol: TCP
    name: http
  selector:
    {{- include "phoenix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix-ws-gateway
