apiVersion: v1
kind: Service
metadata:
  name: phoenix-prediction-monitor
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix-prediction-monitor
spec:
  type: ClusterIP
  ports:
  - port: 8075
    targetPort: 8075
    protocol: TCP
    name: http
  selector:
    {{- include "phoenix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix-prediction-monitor
