apiVersion: v1
kind: Service
metadata:
  name: phoenix-discord-ingestion
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix-discord-ingestion
spec:
  type: ClusterIP
  ports:
  - port: 8060
    targetPort: 8060
    protocol: TCP
    name: http
  selector:
    {{- include "phoenix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: phoenix-discord-ingestion
